### ISSUE TITLE
Broken in post-release patch 1.14.0-f8, throws System.NullReferenceException

### ISSUE THREAD

**Issue by jkuhlm** [algernon-A/TransitVehicleSpawnDelay#8]
[output_log.txt](https://github.com/algernon-A/TransitVehicleSpawnDelay/files/8048343/output_log.txt)

**Comment by algernon-A** [comment]
Thanks for that.  Interestingly, I can't find any errors relating to this mod in that log.

What I do find is a number of very strange unrelated errors that I would not expect to see.

I also note that you're using Network Extensions 3.  Please note that that mod (and others by that person) has been found to **deliberately break** other mods.  Consequently, that means that any breakage when using that mod (or the others) can't reliably be debugged.

More on that issue from the TM:PE team on their [workshop page](https://steamcommunity.com/workshop/filedetails/discussion/1637663252/4731597528356140067/). and also note the [currently leading article](https://www.reddit.com/r/CitiesSkylines/comments/spo2mn/alert_stop_using_network_extension_3_harmony/) on the r/CitiesSkylines reddit.

So, the important question is: does this keep happening when you unsubscribe from all mods from that person (including Network Extensions 3)?

**Comment by jkuhlm** [comment]
The NullReferenceException has returned. I no longer have NE3, I don't have any other mods from that person.   I've confirmed that the Exception is related to Transit Vehicle Spawn Delay 1.2 in some way.  The error vanished when I unsub Transit Vehicle Spawn Delay 1.2 and returns when I resub it.  New log attached.  Thanks in advance. 
[output_log.txt](https://github.com/algernon-A/TransitVehicleSpawnDelay/files/8051712/output_log.txt)

**Comment by algernon-A** [comment]
Thanks for the new log - all the strange errors are now gone, and it's a lot clearer about what's going on!  I think I can see the issue now, and will aim to have an update out soon.

**Comment by algernon-A** [comment]
Believed fixed in 0b5a92119ccfbdfb5d3a79e9fa28be8ba06475c1; leaving this open for now as I cannot reproduce the issue myself and will need @jkuhlm to confirm if it works or not.

**Comment by jkuhlm** [comment]
It's fixed!   I've let the game run for over 8 hours with no more errors.  Thanks.
